# Generated by Django 2.2 on 2020-12-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.CharField(max_length=100)),
                ('store_code', models.CharField(max_length=100)),
                ('old_plan_name', models.CharField(max_length=100)),
                ('old_plan_speed', models.CharField(max_length=100)),
                ('old_plan_quota', models.CharField(max_length=100)),
                ('old_plan_price', models.CharField(max_length=100)),
                ('new_plan_name', models.CharField(max_length=100)),
                ('new_plan_speed', models.CharField(max_length=100)),
                ('new_plan_quota', models.CharField(max_length=100)),
                ('new_plan_price', models.CharField(max_length=100)),
                ('number_of_movements', models.CharField(max_length=100)),
            ],
        ),
    ]
