# Generated by Django 2.2 on 2020-12-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='change_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='new_plan_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='new_plan_quota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='new_plan_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='number_of_movements',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='old_plan_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='old_plan_quota',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='plan',
            name='old_plan_speed',
            field=models.IntegerField(),
        ),
    ]
