# Generated by Django 2.2 on 2020-12-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_testupload_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='change_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
