# Generated by Django 2.2 on 2020-12-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0006_auto_20201206_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='change_date',
            field=models.CharField(max_length=100),
        ),
    ]
